version: '3'

services:
  mysql:
    image: "mysql:5.5"
    restart: "always"
    container_name: "${Project}_mysql"
    volumes:
      - ${Data_dir}:/data     
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${Project}

  web:
    build: Runtime/Docker
    image: web:${VERSION_MAJOR}.${VERSION_MINOR}
    restart: "always"
    container_name: ${Project}
    command: "npm start"
    volumes:
      - ${Data_dir}/:/data      
      - .:/web
    links:
      - mysql
    ports:
      - "443:443" 
