version: '3.1'

services:
  web:
    build: build
    image: web:${VERSION_MAJOR}.${VERSION_MINOR}
    restart: "always"
    container_name: ${Project}
    command: "npm start"
    volumes:
      - ${Data_dir}/:/data      
      - .:/web
    network_mode: "host" 
